---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    openshift.io/description: "Microshift Hello Demo"
    openshift.io/display-name: "Microshift Hello Demo"
