---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-microshift
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.host }}
  to:
    kind: Service
    name: hello-microshift
  port:
    targetPort: 8080
  wildcardPolicy: None
